⚡ Parse UA from request, set media query
algodex/algodex-mailbox pull request #134
Opened 2022-04-01 20:54 UTC by treasurechic

# ℹ Overview

### 📝 Related Issues

2022-04-01 20:58 UTC, atrefonas requested changes

2022-04-01 20:58 UTC, atrefonas commented on pages/_document.js
> +  console.log(deviceType)
Please change to console.debug

2022-04-01 21:00 UTC, PhearZero commented on pages/_document.js
> +  console.log(deviceType)
It's SSR only

2022-04-01 22:19 UTC, atrefonas approved these changes

2022-04-01 22:28 UTC, PhearZero approved these changes

2022-04-01 22:50 UTC, merged

2022-10-11 07:34 UTC, atrefonas commented
Ohh, makes sense. Since it's _document.js. Got it. I don't mind then.

On Fri, Apr 1, 2022 at 5:00 PM Michael J Feher ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pages/_document.js
> <https://github.com/algodex/algodex-mailbox/pull/134#discussion_r840916406>
> :
>
> > @@ -88,9 +90,10 @@ MyDocument.getInitialProps = async (ctx) => {
>        dangerouslySetInnerHTML={{ __html: style.css }}
>      />
>    ))
> -
> +  console.log(deviceType)
>
> It's SSR only
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/algodex/algodex-mailbox/pull/134#discussion_r840916406>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARL6JW7WRTTRVWLRLNZXP63VC5PYNANCNFSM5SJYQGFQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>