Issue 143 ✨ feature add landing page in light mode
algodex/algodex-mailbox pull request #157
Opened 2022-04-08 17:45 UTC by treasurechic

# ℹ Overview

### 📝 Related Issues

-- closes #143

2022-04-08 17:52 UTC, atrefonas requested changes
![image](https://user-images.githubusercontent.com/72869083/162495349-b4242aec-5704-4099-a0ca-07aecccf39ca.png)


This picture is missing

2022-04-08 17:52 UTC, atrefonas commented on components/LandingPage/Hero.js
> +                  <strong>Try on testnet Now:</strong>
Use the /lib function to check what network you are on, and change to Mainnet or Testnet depending on this.

2022-04-08 17:53 UTC, atrefonas commented on components/LandingPage/Hero.js
> +                  Useful when sending to one wallet or thousands. <br /> <br />
Change from 'thousands' to 'hundreds' for now.

2022-04-08 17:55 UTC, atrefonas commented
Questions 2 and 3 are the same.

The answers to all 3 are the same. Please fix

![image](https://user-images.githubusercontent.com/72869083/162495735-d6c3057d-48f1-4b6e-a161-c60e4a05fc83.png)

2022-04-08 17:56 UTC, atrefonas commented
![image](https://user-images.githubusercontent.com/72869083/162495976-be7a58da-8f1a-4614-ab79-c29859903986.png)


The logo is missing

2022-04-08 18:26 UTC, atrefonas commented
"Learn to use Algodex Mailbox using our guide."

Needs a link to the guide

2022-04-08 18:56 UTC, atrefonas commented
Can you reduce the spacing between the unexpanded boxes? To be the same as the spacing between the expanded boxes.

![image](https://user-images.githubusercontent.com/72869083/162504558-259ef382-ce26-48d1-b3ed-b25421faeae2.png)

2022-04-08 18:59 UTC, atrefonas commented
The colors are wrong. It should look like this:

![image](https://user-images.githubusercontent.com/72869083/162506654-3f9d15f8-ac4a-4160-ae6d-eb120d0c43e6.png)

2022-04-08 19:03 UTC, treasurechic commented
No, the colors are not wrong, https://www.figma.com/file/3mUNzhDN7whCLAMlykP8UY/Mailbox-Landing-Page?node-id=36%3A2

I had a discussion with  Steph on the colors, told her it will not make sense to have a different color on the landing page and have a different one on the dashboard. So she created the theme for purple which is the existing color palette. 

I can change the color to the grey theme if that is what you want, but that means we have to change the whole theme to grey so we can have a unigue color code with the dashboard

2022-04-08 19:05 UTC, atrefonas commented
Your box is too small, the fonts are too small, and should also be under part of the graphic design.

Design:

![image](https://user-images.githubusercontent.com/72869083/162508055-6a184b24-75c6-4624-a0a4-4671741a3077.png)



Yours:

![image](https://user-images.githubusercontent.com/72869083/162508153-3814778b-c098-49fd-b276-69db7bc755af.png)

2022-04-08 19:09 UTC, treasurechic commented
Oh, large screens...will update

2022-04-08 19:11 UTC, atrefonas commented
Yes, please make sure it looks good on every screen size.

2022-04-08 19:14 UTC, atrefonas commented
It doesn't work in Spanish mode. Either disable Spanish or provide translations.

https://algodex-mailbox-mo3yq2i08-algodex-dev.vercel.app/es#user-guide

2022-04-08 19:18 UTC, treasurechic commented
It works for spanish, I just can't translate the whole page, that is why it is not reflecting on the whole page(I was hoping the language translator will do that).

Here is an example of where it works currently
![image](https://user-images.githubusercontent.com/46996915/162509762-82a2cbd4-1984-4668-a9af-42456f2ab2ad.png)

2022-04-08 19:24 UTC, atrefonas commented
Can you use Google Translate to translate the whole page?

2022-04-08 19:39 UTC, stephclarkga commented
I'm not against changing the whole theme to gray if everyone agrees since I think it ties into the original Algodex colors better but I did update this to match the colors Adesola provided were already in use. 

Couple things that haven't been mentioned yet: 

This third box ended up a bit bigger than the others - due to padding around the text maybe? Text should be moved up a bit so the box is the same as the others
<img width="1192" alt="Screen Shot 2022-04-08 at 3 33 08 PM" src="https://user-images.githubusercontent.com/59464107/162511763-e27b0d6a-9a61-4f95-868e-9a2f0b497d30.png">

"Mailbox User Guide" should link to https://about.algodex.com/docs/algodex-mailbox-user-guide/
And only "Mailbox User Guide" should be underlined to show it's a link.
<img width="1021" alt="Screen Shot 2022-04-08 at 3 30 21 PM" src="https://user-images.githubusercontent.com/59464107/162511388-6ba60715-81a2-464a-a163-61f9a0bb06cd.png">

I think we can remove the "Careers" and "Partnerships" from the footer right now until we have pages they can link to. Also where did the email list join section go?
<img width="1312" alt="Screen Shot 2022-04-08 at 3 36 51 PM" src="https://user-images.githubusercontent.com/59464107/162513728-126bd99f-1a91-47b2-bdb7-2d4c046611ff.png">

2022-04-08 19:42 UTC, treasurechic commented
@stephclarkga , the email input is hidden for now until it is functional

2022-04-08 19:46 UTC, stephclarkga commented
Also, in the header, let's have "User Guide" link to https://about.algodex.com/docs/algodex-mailbox-user-guide/

And in the FAQ, can you make the questions bold like this? It's easier to read when the question text is different than the answer
<img width="638" alt="Screen Shot 2022-04-08 at 3 46 23 PM" src="https://user-images.githubusercontent.com/59464107/162516171-0277b889-c007-47a5-a4af-71cd1b8b2d32.png">

2022-04-08 19:47 UTC, treasurechic commented
Everything is noted, I will adjust.

2022-04-08 19:48 UTC, stephclarkga commented
Awesome, it looks great just those few minor things!

2022-04-12 13:32 UTC, stephclarkga approved these changes

2022-04-12 16:37 UTC, merged