Issue 138 ✨ feature add status bar or other indicator when sending lots of assets to show the progress
algodex/algodex-mailbox pull request #167
Opened 2022-04-14 11:31 UTC by treasurechic

# ℹ Overview

### 📝 Related Issues

closes #138

2022-04-14 15:12 UTC, PhearZero requested changes
Events are working but they can be leveraged to provide the actual data and not just an estimate. 

See the comments to extract the current progress from the inner helpers to the outer `useSendAsset` effect. 

- [x] Emit progress, status, and total for each step of the process
- [x] Remove any events from `send` since the `helpers` is the only place that needs them

2022-04-14 15:12 UTC, PhearZero commented on components/SendAssetProgress.js
> +const SendAssetProgress = ({ progress }) => {
This component shouldn't be necessary, use `<LinearProgressWithLabel>` directly and emit the `progress`, `status` and `total` as a part of the event

2022-04-14 15:12 UTC, PhearZero commented on hooks/useSendAsset.js
> +  const [progress, setProgress] = useState('uninitialized')
- [x] Revert this back to `status` and use another state for `progress` that has a initial state of `0`.  
- [x] Introduce a new state called `total` which is a number with a initial state of 0. 
- [x] Introduce a new state called `hideProgress` with an effect that sets the value based on state

2022-04-14 15:12 UTC, PhearZero commented on components/LinearProgressWithLabel.js
> +  const { value, report } = props
The progress bar should consume the payload from the event without any Wrappers like `<SendAssetProgress>`

- [x] Refactor `value` to `progress` since we have two components, it's not clear what the value is for
- [x] Refactor `report` to `status` to keep a consistent naming with the event payload.
- [x] Introduce `hideProgress`
- [x] Introduce `total` for sizing the progress.
   - [x] Normalize `value` for the `total` https://mui.com/material-ui/react-progress/#non-standard-ranges
- [x] Have at least one required property, component should not be able to return an empty fragment.

2022-04-14 15:12 UTC, PhearZero commented on hooks/useSendAsset.js
> +  return {progress}
Return `progress`, `status`, `hideProgress` and `total`

2022-04-14 15:12 UTC, PhearZero commented on lib/helper.js
> +    events.emit('sending-assets-event', {status: 'signing2'})
- [x] scope the events based on the work that they are doing . These events should be called `sign-with-my-algo`
- [x] signing2 is an unnecessary emit, we have already emitted `signed` at this point and there is no work done between the two events.
- [x] Emit the progress, status and total from after the signLogicSigTransactionObject using the following:

```jsx
for (let i = 0; i < allTxns.length; i++) {
  const trans = allTxns[i]
  if (trans.lsig) {
    let signedTxn = algosdk.signLogicSigTransactionObject(
      trans.unsignedTxn,
      trans.lsig
    )
    events.emit('sign-with-my-algo', {status: 'Signing Transactions...', progress: i, total: innerTxnsForSigning.length})
    trans.signedTxn = signedTxn.blob
  }
}
```

2022-04-14 15:12 UTC, PhearZero commented on lib/send_assets.js
> +      events.emit('sending-assets-event', { status: 'signing1' })
- [x] Unnecessary event, use 'sign-with-my-algo' events from `./helpers`

2022-04-14 15:12 UTC, PhearZero commented on lib/send_assets.js
> +      events.emit('sending-assets-event', { status: 'loading' })
- [ ] Unnecessary event, we only need events from inside of each step and not the overall progress.

2022-04-14 15:12 UTC, PhearZero commented on lib/send_assets.js
> +      events.emit('sending-assets-event', { status: 'complete' })
- [ ] Unecissary event, needs to be inside of `sendAllTransactions` to emit the actual status of sending transactions. The event can be called `send-all-transactions` and it should include the `total` and `progress` values in the payload

2022-04-14 15:12 UTC, PhearZero commented on lib/send_assets.js
> +      events.emit('sending-assets-event', { status: 'stop' })
- [ ] Unnecessary event, errors must be handled `thrown`

2022-04-14 15:30 UTC, treasurechic commented on components/SendAssetProgress.js
> +const SendAssetProgress = ({ progress }) => {
@PhearZero Everything is noted 👍🏽

The event in send is actually necessary, it tells me when it is getting the balance and all(first step).
It also tells me when it is completed or failed especially when there is an error.(when to hide the progress).

2022-04-14 15:31 UTC, stephclarkga requested changes
I imagined that the progress bars would actually progress to show progress of each step. 
Right now it looks like the first step starts at 20% and never changes so it doesn't give the user much feedback. This bar should start from 0 and end full once this step is complete.
Second step is sending to the MyAlgo bridge and should also have a bar start at 0 and go full. (This step could be combined with the first progress bar if it takes less than about 4 seconds on average - I'm not sure what the time for this step really is but if someone knows that would be great)
Third step triggers the MyAlgo Signing UI and it'd be nice to have an indefinite loading bar on the site with the title "Awaiting Signature" title since this informs the customer that we are waiting on them.
Final step is sending the transactions with another progress bar that starts at 0 and ends full. It would be great if the number of transactions completed can be the label to the side of the bar (eg. 15/27 since this further confirms the number of transactions being sent - starts at 0/X and ends X/X instead of always out of 100)

2022-04-14 15:51 UTC, treasurechic commented
> I imagined that the progress bars would actually progress to show progress of each step since when sending to many wallets some of these steps can take a while so we need to give some active feedback. Right now it looks like the first step starts at 20% and never changes so it doesn't give the user much feedback. This bar should start from 0 and end full once this step is complete. Second step is sending to the MyAlgo bridge and should also have a bar start at 0 and go full. (This step could be combined with the first progress bar if it takes less than about 4 seconds on average - I'm not sure what the time for this step really is but if someone knows that would be great) Third step triggers the MyAlgo Signing UI and it'd be nice to have an indefinite loading bar on the site with the title "Awaiting Signature" title since this informs the customer that we are waiting on them. Final step is sending the transactions with another progress bar that starts at 0 and ends full. It would be great if the number of transactions completed can be the label to the side of the bar (eg. 15/27 since this further confirms the number of transactions being sent - starts at 0/X and ends X/X instead of always out of 100)

Oh, I get that, I am working on that

2022-04-15 15:37 UTC, PhearZero requested changes
Everything looks good 🕺! Events and hooks look perfect. Two minor changes

- [ ] Remove error emit
- [ ] Always return an element from LinearProgressWithLabel

2022-04-15 15:37 UTC, PhearZero commented on lib/send_assets.js
> +      events.emit('Error', {
This emit can be removed and you can instance check the return value of `send`. You can also export the setters from `useSendAsset` for Inversion of Control.

Aside: The current error passing is an anti-pattern. We do not want to add more technical debt to it with an evented system. Refactor to use `instanceof` checking in the consumers of `send`

```jsx
//./hooks/useSendAsset

return  return { progress, status, total, hideProgress, setStatus, setHideProgress, setProgress }
``` 

```jsx
// ./pages/send-assets

 const { progress, status, total, hideProgress,  setStatus, setHideProgress, setProgress } = useSendAsset()

const responseData = await SendAssets.send(
  assetId,
  wallet,
  csvTransactions
)
      
if(responseData instanceof Error){
  setStatus('Sorry, an error has ocurred')
  setHideProgress(true)
}
```

2022-04-15 15:37 UTC, PhearZero commented on components/LinearProgressWithLabel.js
> +      {!hideProgress && (
- [ ] LinearProgressWithLabel should always show a label and only hide the `<LinearProgress>` Box wrapper with `hideProgress`

Move hide progress to the `<LinearProgress>` component. This component would return an empty fragment which is not very useful. Hide this component from where it is being used based on the current state.

```jsx
// ./pages/send-assets
const hasStatusBar = useMemo(()=>{
    return typeof status === 'undefined' // add move conditions
}, [status])

{ hasStatusBar && <LinearProgressWithLabel
  status={status}
  progress={progress}
  total={total}
  hideProgress={hideProgress}
/>}

```

2022-04-15 15:38 UTC, PhearZero commented on components/SendAssetProgress.js
> +const SendAssetProgress = ({ progress }) => {
We can remove the `send` emitters since JavaScript can natively handle the `Error` response of `send` without the need of events.

2022-04-15 20:46 UTC, PhearZero approved these changes
LGTM 🕺

2022-04-18 04:33 UTC, stephclarkga commented
The progress bar is still loading weird for me (want to make sure I'm using the latest preview - let me know if this isn't the case!). Once I hit send and the bar comes up it starts at 75/100 (I think I saw 50/100 one time though) and the bar sits at that point so it's not very useful. Is there a way to show progress more consistently here?

And then when the MyAlgo popup comes up to sign, the progress bar should change to an indeterminate bar with a title "Awaiting Signature" to inform the user we are waiting on them. I'm not seeing this step at all anymore (I think I did before though but not sure)

And one other small thing - for the final step where it is sending, is it possible to have the label on the progress bar be "number of transactions sent/total" so for example if user is sending 48 transactions and it's halfway done, the label is at "24/48"? This reaffirms to the customer that everything was processed correctly

2022-04-18 12:09 UTC, treasurechic commented
> The progress bar is still loading weird for me (want to make sure I'm using the latest preview - let me know if this isn't the case!). Once I hit send and the bar comes up it starts at 75/100 (I think I saw 50/100 one time though) and the bar sits at that point so it's not very useful. Is there a way to show progress more consistently here?
> 
> And then when the MyAlgo popup comes up to sign, the progress bar should change to an indeterminate bar with a title "Awaiting Signature" to inform the user we are waiting on them. I'm not seeing this step at all anymore (I think I did before though but not sure)
> 
> And one other small thing - for the final step where it is sending, is it possible to have the label on the progress bar be "number of transactions sent/total" so for example if user is sending 48 transactions and it's halfway done, the label is at "24/48"? This reaffirms to the customer that everything was processed correctly


@stephclarkga  The progress bar might look so fast if your network is really good. It actually starts from the beginning. The progress of the status is quite visible when you are sending to lots of addresses, like 6-8 addresses. If you need some, I can send you 8 addresses to test with.

"Waiting for user signature via the MyAlgo GUI" step has been added in as well. Here is the updated link to test again: https://algodex-mailbox-loqy1qtdr-algodex-dev.vercel.app/send-assets

2022-04-18 15:16 UTC, stephclarkga commented
Thanks for confirming! I've tested with a list of 20 - I must just have good internet. Thanks!

2022-04-18 15:16 UTC, stephclarkga approved these changes

2022-04-18 16:38 UTC, merged