Issue 12 ✨ feature in send asset show the asset balance of the sender
algodex/algodex-mailbox pull request #29
Opened 2022-03-07 18:21 UTC by treasurechic

# ℹ Overview

### 📝 Related Issues

2022-03-07 18:31 UTC, atrefonas requested changes
Please show the balance when I fill in these two parts of the form:

![image](https://user-images.githubusercontent.com/72869083/157095873-222aa544-9492-4355-8e68-4d55bf8a4899.png)

2022-03-07 18:44 UTC, atrefonas commented on pages/send-asset.js
> +            'An error occurred while getting your asset balance, pls ensure you enter a valid asset id',
Can you change this to 'please' instead of 'pls'?

2022-03-07 21:14 UTC, treasurechic commented on pages/send-asset.js
> +            'An error occurred while getting your asset balance, pls ensure you enter a valid asset id',
Ok

2022-03-09 00:04 UTC, atrefonas requested changes

2022-03-09 00:04 UTC, atrefonas commented on pages/send-asset.js
> +      console.log('sec', wallet, assetId)
Can you remove or comment our the console.log's?

2022-03-09 00:12 UTC, atrefonas approved these changes

2022-03-09 00:14 UTC, merged